# Data parameters
# Merged from config.yaml and config.yml

data_dir: "../processed_data"  # This is where our raw data files are
price_cols: ["open", "high", "low", "close", "volume"]
timeframes: ["15Second", "1minute", "15minute", "1hour", "4hours"]  # All available timeframes

data:
  raw_dir: "../processed_data"  # Same as data_dir since that's where our files are
  processed_dir: "processed_data"  # Where the algorithm will save its processed data
  features_dir: "features"
  symbol: "BTCUSDT"
  timeframe_files:
    "15Second": "15Second.parquet"  # Just the filename, path is handled by data_dir
    "1minute": "1minute.parquet"
    "15minute": "15minute.parquet"
    "1hour": "1hour.parquet"
    "4hours": "4hours.parquet"
  start_date: "2023-01-01"
  end_date: "2024-01-01"

# Feature engineering parameters
feature_engineering:
  rolling_windows: [5, 10, 20, 50, 100, 200, 500]  # Extended windows for better feature capture
  cross_indicator_pairs:
    - ["rsi", "macd"]
    - ["volume", "close"]
    - ["bollinger_bands", "momentum"]
    - ["volume_ma", "volume_std"]
    - ["rsi", "volume"]
    - ["macd", "momentum"]
    - ["bollinger_bands", "volume"]
  time_features: ["hour", "minute", "day_of_week", "day_of_month", "month", "quarter"]

# Label generation parameters
label_generation:
  min_move_size: 0.3  # Reduced for 15s timeframe
  max_holding_time: 15  # Reduced for 15s timeframe
  min_holding_time: 1  # Minimum holding time in minutes
  stop_loss: 0.2  # Tighter stop loss for 15s
  take_profit: 0.4  # Adjusted take profit for 15s

labeling:
  threshold: 0.001  # 0.1% return threshold for binary classification
  lookforward: 10   # Number of periods to look forward for label generation

features:
  technical_indicators:
    - rsi
    - macd
    - bollinger_bands
    - momentum
    - volume_ma
    - volume_std
    - volume_ratio
    - high_low_ratio
    - close_open_ratio
    - atr
    - stochastic
    - williams_r
    - cci
    - mfi
    - obv
    - adx
    - ichimoku
  time_features:
    - hour
    - minute
    - day_of_week
    - day_of_month
    - month
    - quarter

# Model parameters
models:
  lgbm:
    n_trials: 200  # Significantly increased trials for better optimization
    num_leaves: [31, 63, 127]  # Multiple options for optimization
    learning_rate: [0.001, 0.01, 0.05, 0.1]  # Wider range of learning rates
    n_estimators: [500, 1000, 2000]  # Increased for better performance
    max_depth: [6, 8, 10, 12]  # Multiple depth options
    min_child_samples: [10, 20, 50]  # Multiple options
    subsample: [0.6, 0.8, 0.9]  # Multiple options
    colsample_bytree: [0.6, 0.8, 0.9]  # Multiple options
    reg_alpha: [0.01, 0.1, 1.0]  # Multiple options
    reg_lambda: [0.01, 0.1, 1.0]  # Multiple options
    random_state: 42
    n_jobs: -1
    validation_size: 2000  # Increased validation size
    early_stopping_rounds: 50
    verbose: 100
  tft:
    learning_rate: [0.0001, 0.001, 0.01]  # Multiple options
    hidden_size: [64, 128, 256]  # Multiple options
    attention_head_size: [4, 8, 16]  # Multiple options
    dropout: [0.1, 0.2, 0.3]  # Multiple options
    hidden_continuous_size: [32, 64, 128]  # Multiple options
    max_epochs: 100  # Significantly increased epochs
    batch_size: [64, 128, 256]  # Multiple options
    encoder_length: [48, 96, 192]  # Multiple options
    validation_size: 2000
    params:
      loss: "quantile"
    train:
      max_epochs: 100
      batch_size: [64, 128, 256]
      validation_size: 2000
      random_state: 42
      patience: 20  # Early stopping patience
      gradient_clip_val: 1.0
      accumulate_grad_batches: 2

# Rule mining parameters
rule_mining:
  max_rules: 500  # Increased for more comprehensive rule set
  min_support: 0.005  # Lowered for more rules
  min_confidence: 0.4  # Adjusted for better balance
  max_indicators: 3  # Increased for more complex rules
  max_combinations: 500  # Increased for more combinations
  min_precision: 0.4  # Adjusted for better balance
  min_recall: 0.4  # Adjusted for better balance

# Backtesting parameters
backtesting:
  n_splits: 10  # Increased for more robust validation
  initial_capital: 100000
  transaction_cost: 0.001  # Added transaction cost
  slippage: 0.0005  # Added slippage

# Logging parameters
logging:
  level: "INFO"
  file: "logs/trading.log"
  tensorboard: true  # Added tensorboard logging
  wandb: true  # Added Weights & Biases logging

# Label parameters
label:
  horizon_minutes: 15
  threshold: 0.001
  dollar_threshold: 10

model:
  models_dir: "models"
  save_best_only: true
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3  # Save top 3 models
  every_n_epochs: 1
  save_last: true 