# paths
data_dir: processed_data               # where your parquet files live
timeframes: ["15Second", "1minute", "15minute", "1hour", "4hours"]
price_cols: [open, high, low, close, volume]

# label: “±$500 in next N minutes”
label:
  horizon_minutes: 60
  dollar_threshold: 500

# train / test split
split:
  train_days: 4
  test_days: 3          # walk-forward automatically handles roll-outs

# modelling
ml:
  lgbm:
    max_evals: 200      # Bayesian optimisation iterations
    early_stopping: 50
  tft:
    max_epochs: 30
    batch_size: 1024
