# Data parameters
# Merged from config.yaml and config.yml

data_dir: "C:/Users/Avi/quant/processed_data"  # Updated path with forward slashes
price_cols: ["open", "high", "low", "close", "volume"]
timeframes: ["15Second", "1minute", "15minute", "1hour", "4hours"]  # All available timeframes

data:
  raw_dir: "C:/Users/Avi/quant/processed_data"  # Updated path with forward slashes
  processed_dir: "processed_data"  # Where the algorithm will save its processed data
  features_dir: "features"
  symbol: "BTCUSDT"
  timeframe_files:
    "15Second": "15Second.parquet"  # Just the filename, path is handled by data_dir
    "1minute": "1minute.parquet"
    "15minute": "15minute.parquet"
    "1hour": "1hour.parquet"
    "4hours": "4hours.parquet"
  start_date: "2023-01-01"
  end_date: "2024-01-01"

# Feature engineering parameters
feature_engineering:
  rolling_windows: [10, 20, 50, 100, 200, 500, 1000]  # Extended windows
  cross_indicator_pairs:
    - ["rsi", "macd"]
    - ["volume", "close"]
    - ["bollinger_bands", "momentum"]
    - ["volume_ma", "volume_std"]
    - ["rsi", "volume"]
    - ["macd", "momentum"]
    - ["bollinger_bands", "volume"]
  time_features: ["hour", "minute", "day_of_week", "day_of_month", "month", "quarter"]

# Label generation parameters
labeling:
  threshold: 0.002  # Increased to 0.2% for more significant moves
  lookforward: 30   # Increased to 30 periods for better prediction horizon
  min_move_size: 0.002  # Aligned with threshold
  max_holding_time: 30  # Aligned with lookforward
  min_holding_time: 5   # Minimum holding time in periods
  stop_loss: 0.003     # 0.3% stop loss
  take_profit: 0.006   # 0.6% take profit

features:
  technical_indicators:
    - rsi
    - macd
    - bollinger_bands
    - momentum
    - volume_ma
    - volume_std
    - volume_ratio
    - high_low_ratio
    - close_open_ratio
    - atr
    - stochastic
    - williams_r
    - cci
    - mfi
    - obv
    - adx
    - ichimoku
  time_features:
    - hour
    - minute
    - day_of_week
    - day_of_month
    - month
    - quarter

# Model parameters - Optimized for long-term training (1-2 years)
models:
  tft:
    learning_rate: 0.0001  # Lower learning rate for stability
    hidden_size: 512      # Larger model for complex patterns
    attention_head_size: 16  # More attention heads
    dropout: 0.3          # Higher dropout for regularization
    hidden_continuous_size: 256
    max_epochs: 500       # More epochs for complex data
    batch_size: 2048      # Large batch size for 5070
    encoder_length: 300   # Longer sequence for better context
    validation_size: 10000 # More validation data
    params:
      loss: "quantile"
    train:
      max_epochs: 500
      batch_size: 2048
      validation_size: 10000
      random_state: 42
      patience: 25        # More patience for complex training
      gradient_clip_val: 0.1
      accumulate_grad_batches: 1  # No accumulation needed with large batch
      precision: 16       # Mixed precision
      accelerator: "gpu"
      devices: 1
      strategy: "auto"
      # Learning rate scheduling
      lr_scheduler: "cosine"
      lr_scheduler_params:
        warmup_epochs: 10
        min_lr: 1e-6
      # Advanced training features
      gradient_clip_algorithm: "norm"
      deterministic: false
      enable_progress_bar: true
      log_every_n_steps: 50

# Backtesting parameters
backtesting:
  n_splits: 10
  initial_capital: 100000
  transaction_cost: 0.001
  slippage: 0.0005
  commission: 0.001
  min_trades: 100
  max_drawdown: 0.2

# Logging parameters
logging:
  level: "INFO"
  file: "logs/trading.log"
  tensorboard: true
  wandb: true
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"

# Model saving parameters
model:
  models_dir: "models"
  save_best_only: true
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  every_n_epochs: 1
  save_last: true
  version: "1.0.0"
  metadata:
    framework: "pytorch"
    model_type: "tft"
    trading_mode: "paper"

# Label parameters
label:
  horizon_minutes: 15
  threshold: 0.001
  dollar_threshold: 10

monitoring:
  # Logging settings
  log_level: "INFO"
  log_file: "logs/trading.log"
  metrics_file: "logs/metrics.json"
  
  # Alert thresholds
  risk_limits:
    max_drawdown: 0.05  # 5% max drawdown
    max_position_size: 0.20  # 20% of capital
    max_daily_loss: 0.02  # 2% daily loss
    max_leverage: 3.0  # Maximum leverage
    min_sharpe: 1.0  # Minimum Sharpe ratio
    max_correlation: 0.7  # Maximum correlation with market
    
  # Performance monitoring
  performance:
    lookback_period: 20  # Days to look back for performance metrics
    min_win_rate: 0.45  # Minimum win rate
    min_profit_factor: 1.2  # Minimum profit factor
    max_drawdown_duration: 10  # Maximum drawdown duration in days
    
  # Regime detection
  regime:
    volatility_threshold: 0.02  # 2% volatility threshold
    correlation_threshold: 0.5  # Correlation threshold
    min_samples: 100  # Minimum samples for regime detection
    
  # Alert channels
  alerts:
    email:
      enabled: true
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      sender_email: ""  # Add your email
      sender_password: ""  # Add your app password
      recipient_emails: []  # Add recipient emails
      
    slack:
      enabled: false
      webhook_url: ""  # Add your Slack webhook URL
      
  # Reporting
  reporting:
    daily_report_time: "23:00"  # Time to generate daily report
    report_metrics:
      - "returns"
      - "sharpe_ratio"
      - "drawdown"
      - "win_rate"
      - "profit_factor"
      - "position_sizes"
      - "risk_metrics"

portfolio_analytics:
  risk_free_rate: 0.02  # Annual risk-free rate
  benchmark: "BTC-USD"  # Benchmark symbol for performance comparison
  metrics:
    storage_duration: 86400  # 24 hours in seconds
    report_duration: 2592000  # 30 days in seconds
    max_returns_history: 1000  # Maximum number of returns to store
  risk_limits:
    max_leverage: 3.0
    min_margin_level: 150.0  # Percentage
    max_drawdown: 0.15  # 15%
    max_var_95: 0.02  # 2% daily VaR
  performance_thresholds:
    min_sharpe: 1.0
    min_sortino: 1.5
    min_information_ratio: 0.5
    min_win_rate: 0.5
    min_profit_factor: 1.5
  reporting:
    daily_report_time: "23:59:59"
    metrics_to_track:
      - total_value
      - daily_pnl
      - daily_return
      - sharpe_ratio
      - sortino_ratio
      - max_drawdown
      - win_rate
      - profit_factor
      - leverage
      - margin_level
      - var_95
      - cvar_95
      - information_ratio
      - tracking_error 